# Netlify部署配置文件
[build]
  # 构建命令
  command = "hugo --gc --minify"
  # 发布目录
  publish = "public"

# Hugo版本
[build.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_ENABLEGITINFO = "true"

# 生产环境设置
[context.production.environment]
  HUGO_ENV = "production"

# 分支部署设置
[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# 重定向规则
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# 头部设置（安全和性能优化）
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# 缓存设置
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
